import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import ConnectedWallet from '../components/ConnectedWallet';
import ConnectWalletButton from '../components/ConnectWalletButton';
import styles from '../styles/Home.module.css';
import useMetaMask from '../useContext/useMetaMask';

const Home = () => {
  const [metamask, setMetamask] = useState<any>();

  const router = useRouter();

  const handleCoinClick = () => {
    router.push('Coins');
  };

  const useHook = async () => {
    const metamask = await useMetaMask();
    setMetamask(metamask);
  };

  useHook();

  return (
    <div className={styles.container}>
      {metamask ? (
        <ConnectedWallet address={metamask.account}></ConnectedWallet>
      ) : (
        <ConnectWalletButton></ConnectWalletButton>
      )}

      <Head>
        <title>Coinwatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/crypto-icon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} onClick={handleCoinClick}>
          Welcome to <a>Coinwatch</a>
        </h1>

        <p className={styles.description} onClick={handleCoinClick}>
          Get started
          <a>
            <img className={styles.icon} src="/crypto-icon.png" alt=""></img>
          </a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/pedrobrun"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Me
        </a>
      </footer>
    </div>
  );
};

export default Home;
